config/routes.rb
Rails.application.routes.draw do
  root to: "articles#index"
  resources :articles, only: %i(index show)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	scope :recent_first, -> { order(created_at: :desc) }

  def to_partial_path
    "articles/#{view_id}"
  end

  def colour
    @_colour ||= Colour.sample
  end
end

app/models/article_coming_soon.rb
class ArticleComingSoon
  def title
    "I need to write more things..."
  end

  def colour
    "gray"
  end
end

app/models/code_snippet.rb
class CodeSnippet
  FORMATTER = Rouge::Formatters::HTMLLineTable.new(Rouge::Formatters::HTML.new, gutter_class: "hidden")
  LEXERS = {
    ruby: Rouge::Lexers::Ruby.new,
    shell: Rouge::Lexers::Shell.new,
    erb: Rouge::Lexers::ERB.new,
    js: Rouge::Lexers::Javascript.new
  }

  def initialize(language, source_code)
    @language = language
    @source_code = source_code
  end

  def to_html
    FORMATTER.format(lexer.lex(left_aligned_source_code)).html_safe
  end

  private

    attr_reader :language, :source_code

    def lexer
      LEXERS[language]
    end

    def left_aligned_source_code
      lines.map do |line|
        line[(first_line_indentation - 1)..-1]
      end.join("\n")
    end

    def lines
      @_lines ||= split_lines
    end

    def split_lines
      source_code.split("\n").reject(&:empty?)
    end

    def first_line_indentation
      @_first_line_indentation ||= calculate_first_line_indentation
    end

    def calculate_first_line_indentation
      lines.first[/\A */].size
    end
end

app/models/colour.rb
class Colour
  COLOURS = ["red", "yellow", "green", "blue", "indigo", "purple", "pink"].freeze

  def self.sample
    COLOURS.sample
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  ROW_SIZE = 4

  def show 
    @article = Article.find(params[:id])
  end

  def index
    @articles = articles + top_ups
  end

  private

    def articles
      @_articles ||= fetch_articles
    end

    def fetch_articles
      Article.recent_first
    end

    def top_ups
      [ArticleComingSoon.new] * empty_row_positions
    end

    def empty_row_positions
      if row_positions_filled > 0
        ROW_SIZE - row_positions_filled
      else
        0
      end
    end

    def row_positions_filled
      articles.length % ROW_SIZE
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def icon(name, **options)
    inline_svg_pack_tag "media/images/#{name}.svg", options
  end
end

app/helpers/article_helper.rb
module ArticleHelper
  def article_card_colour_classes(article)
    "bg-#{article.colour}-200 hover:bg-#{article.colour}-600 hover:text-#{article.colour}-200"
  end

  def italic(text = nil)
    tag.span class: "italic" do
      text || yield
    end
  end

  def strike(text = nil)
    tag.del do
      text || yield
    end 
  end

  def title(text = nil)
    tag.div class: "text-5xl mb-2" do
      text || yield
    end
  end

  def subtitle(text = nil)
    tag.div class: "text-3xl mb-2" do
      text || yield
    end
  end

  def para(text = nil, extra_class: "")
    tag.div class: "text-base mb-4 #{extra_class}" do
      text || yield
    end
  end

  def line
    tag.div class: "border-b border-solid border-gray-200"
  end

  def list(&block)
    items = capture(&block).strip.split("\n")

    tag.ul class: "mt-4" do
      items.each do |item|
        concat(tag.li item.html_safe)
      end
    end
  end

  def inline_code(text = nil)
    tag.pre class: "bg-gray-200 inline" do
      text || yield
    end
  end

  def code(language:, &block)
    source_code = capture(&block)

    tag.div class: "highlight bg-gray-100 my-2 text-sm overflow-scroll" do
      CodeSnippet.new(language, source_code).to_html
    end
  end

  def link_to(*args, **options)
    options = options.reverse_merge(class: "text-blue-600 hover:underline")
    super(*args, **options)
  end

  def quote(&block)
    text = capture(&block).strip

    para extra_class: "ml-4" do
      italic "\"#{text}\""
    end
  end
end

app/views/application/_header.html.erb
<div class="border-b border-gray-200 py-6 px-4">
  <div class="md:max-w-2xl md:m-auto flex">
    <div class="flex-1">
      Ollie H-M <span class="align-top leading-none">.</span> <%= link_to "@olliedoodleday", "https://twitter.com/olliedoodleday" %>
    </div>
    <div>
      <%= render "navigation" %>
    </div>
  </div>
</div>

app/views/application/_navigation.html.erb
<%= link_to icon("home", size: "24px"), articles_path, class: "" %>

app/views/articles/_06082022093601_c3a591ff61.html.erb
<% # View for article An Easy Way To Rewrite Commit History with view ID 06082022093601_c3a591ff61 %>

<%= title article.title %>

<%= para do %>
  Sometimes, my commit history is a mess: I'll commit something I didn't mean to, then remove it in the next commit, or a few commits later. Or I'll accidentally miss something from a commit then commit it separately. Or I'll fix something in a follow-up commit, then try a different fix in another commit, and again and again.
<% end %>

<%= para do %>
  A messy commit history isn't always a problem, but sometimes I want or need to be precise about having particular changes in particular commits. For example, at Cookpad, we deploy database migrations in isolation. After a PR that <%= italic "includes" %> a database migration is approved, we open a <%= italic "separate" %> PR to merge only the migration and schema change. This is simpler if we put the migration and schema change in a single commit. We can create a new branch, <%= inline_code "git cherry-pick" %> that commit, and that's it - we've extracted the migration to its own branch ready to open the migration-only PR.
<% end %>

<%= subtitle do %>
  The problem
<% end %>

<%= para do %>
  Re-writing a messy commit history can be difficult. I've spent too much time getting into frustrating tangles with <%= inline_code "git rebase" %>. <%= link_to "Interactive rebase", "https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase" %> is really handy when I want to remove specific commits, combine (i.e. 'squash' or 'fixup') specific commits, or reorder commits. But I've hit a wall with it several times. What if I want to move changes from one commit to another? What if I want to move changes into a new commit? And combine them with other changes from other commits? 😬😅 
<% end %>

<%= para do %>
  Maybe <%= inline_code "git rebase -i HEAD~10" %> does have the answers... but recently I've found an alternative that feels a lot simpler and less painful.
<% end %>

<%= subtitle do %>
  The solution
<% end %>

<%= para do %>
  Suppose you have a branch with a messy commit history called <%= inline_code "cool_feature" %>, and you've already opened a draft PR for that branch.
<% end %>

<%= para do %>
  1. From the branch, merge in <%= inline_code "main" %> to ensure the diff against main is up-to-date:
  <%= code language: :shell do %>
    git checkout cool_feature
    git merge main
  <% end %>
<% end %>

<%= para do %>
  2. Store the difference between <%= inline_code "cool_feature" %> and <%= inline_code "main" %> in a file:
  <%= code language: :shell do %>
    git diff main --patch > "full_diff_compared_with_main"
  <% end %>
<% end %>

<%= para do %>
  3. Delete the branch with the messy commit history and create a new branch with the same name:
  <%= code language: :shell do %>
    git checkout main
    git branch -D cool_feature
    git checkout -b cool_feature
  <% end %>
<% end %>

<%= para do %>
  4. Apply the changes from the file to the new <%= inline_code "cool_feature" %> branch:
  <%= code language: :shell do %>
    git apply "full_diff_compared_with_main"
  <% end %>
<% end %>

<%= para do %>
  5. Now, all of the changes that were in the messy commit history are unstaged in the <%= inline_code "cool_feature" %> branch. You can stage and commit them in any order and grouping you want. I use <%= link_to "Sourcetree", "https://www.sourcetreeapp.com/" %> to visualise what I'm staging and committing and what is still unstaged.
<% end %>

<%= para do %>
  6. Force push the branch to update your draft PR. Only do this when you are happy with the new version of the branch:
  <%= code language: :shell do %>
    git push origin cool_feature -f
  <% end %>
<% end %>

<%= para extra_class: "mb-8" do %>
  No more wrangling <%= inline_code "git rebase" %>. No need to re-write or copy-and-paste your changes. Full flexibility to organse those changes as you want/need.
<% end %>

app/views/articles/_20062021210208_015694c177.html.erb
<% # View for article Hello World with view ID 20062021210208_015694c177 %>

<%= title article.title %>

<%= para do %>
  Welcome to my blog. This is the first thing I'm posting, so it's not much of a blog yet. Sorry. And I have no idea what it will become, because it's mainly an experiment to find out
  <%= list do %>
    a) whether I have anything to say
    b) (if a) whether I find it useful or otherwise rewarding to share those things publicly, and
    c) (if a and b) whether I can find the time to write things regularly
  <% end %>
<% end %>

<%= para do %>
  I decided to try this experiment a few months ago, because every now and then I do have an idea for something I might like to share with The World or my future self - something I've learnt or thought through that might be interesting to others or that I might want crystalised for future reference. But I'm never <%= italic "sure" %> if I'd really like going to the trouble of forming it into a shareable Thing or how I'd feel about it being public and (maybe) seen. And I realised - talking about this pointless uncertainty with a colleague - that the only way to find out is to give it a go. So I committed to starting a blog and finding out, and I set myself a deadline: share a first post before July.
<% end %>

<%= para do %>
  Well, it's nearly the end of June, and this is that first post. It's about this blog: the why (above) and (below) the how.
<% end %>

<%= subtitle do %>
  How I Made This Blog...
<% end %>

<%= para do %>
  I've never had a blog before. I've never used Wordpress. My only technical experience with any blog was helping to put together the bare bones of a <%= link_to "Jekyll", "https://jekyllrb.com" %> site and host it on Github pages for a client at my previous job. 
<% end %>

<%= para do %>
  I was a bit apprehensive about delving into the ocean of blog-building and -hosting tools. I feared a blind Google would be overwhelming. So instead I started by thinking about what a blog really is and the simplest way I could achieve it.
<% end %>

<%= para do %>
  A blog is a site with some pages. Yes, each page could be made from content stored in a database or some filesystem in the cloud. But pretty quickly I decided for me the easiest way to write, format and store an article would be to add an html file into the site repository - or, more precisely, as a (mainly) Rails developer, to add an <%= inline_code "html.erb" %> file into a Rails app.
<% end %>

<%= para do %>
  (This was essentially how I remember the Jekyll blog working that I helped with: add an article by adding a file (written with some nice, convenient markup) into a repo. And I remember liking that simplicity.)
<% end %>

<%= para do %>
  But I could also see the benefits of having articles in a database. For one thing, it would be a lot easier to make updates through a web interface, without editing code and redeploying. But that wasn't really an issue for me - I'm happy enough editing <%= inline_code "html.erb" %> files. 
<% end %>

<%= para do %>
  If articles were in a database, however, I could also easily store information about them (a timestamp, description, title, view count) <%= italic "and" %> create relations between articles and other things like likes, keywords, categories and comments. 
<% end %>

<%= para do %>
  So I wondered if I could both
  <%= list do %>
    a) store the content of each article as a Rails view - which I'd edit locally and deploy - while <%= italic "also" %>
    b) having a record of each article in the database 
  <% end %>
<% end %>

<%= para do %>
  In other words, if I add an article on my machine then redeploy the site, how can I ensure there is a record for the new article in the production database?
<% end %>

<%= para do %>
  First thing's first: when I create a database record for an article, it needs to <%= italic "correspond" %> to the article, which is just a file, whether I've created that record locally in my development database or in production or in other staging environments.
<% end %>

<%= para do %>
  The database record in each environment needs some reference to the article. The identifier can't be the record ID, which could be different in each environment. So I settled on each record having a <%= inline_code "view_id" %> which matches up with the article's filename. An article record in production has the same <%= inline_code "view_id" %> referencing the same file as an article record in my local database.
<% end %>

<%= para do %>
  Next: I need a source of truth, available in every environment, telling me which articles need a corresponding database record and what their <%= inline_code "view_id" %>s are, so that after or during deployment, I can create any missing records. 
<% end %>

<%= para do %>
  This source of truth <%= italic "could" %> be the files themselves. But I though it might also be useful to create records with attributes <%= italic "other" %> than the filename (or <%= inline_code "view_id" %>). So I settled on a yaml file that (currently) lists each article's <%= inline_code "view_id" %> and initial title.
<% end %>

<%= para do %>
  Ultimately, then, adding an article means:
  <%= list do %>
    - adding an entry to the yaml file with a title and <%= inline_code "view_id" %>
    - creating a file with the <%= inline_code "view_id" %> as the filename
    - deploying the change and creating a database record for each entry in the yaml file that doesn't already have a record
  <% end %>
<% end %>

<%= para do %>
  And these steps are smoothed out by some custom rails commands. This one adds the entry to the <%= inline_code "articles.yml" %> file and creates the <%= inline_code "html.erb" %> file with a unique <%= inline_code "view_id" %> set as the filename:
  <%= code language: :shell do %>
    bin/rails add_article:execute --title="Hello World"
  <% end %>
  This one (run in each environment) ensures each article has a record in the database with the correct <%= inline_code "view_id" %>:
  <%= code language: :shell do %>
    bin/rails sync_articles:execute
  <% end %>
<% end %>

<%= para do %>
  So far, articles only have a title and a timestamp. No tags, likes, categories or comments. But each article is both a file (which I can edit locally) and a record in an <%= inline_code "articles" %> table. So listing articles means fetching <%= inline_code "Article.recent_first" %>. Clicking an article takes you to <%= inline_code "/articles/:id" %>, where we fetch the correct article using <%= inline_code "Article.find(params[:id])" %>. 
<% end %>

<%= para do %>
  In the Article model, we define
  <%= code language: :ruby do %>
    def to_partial_path
      "articles/#{view_id}"
    end
  <% end %>
  which means we can render the article (in <%= inline_code "/articles/show.html" %>) like this:
  <%= code language: :erb do %>
    <%%= render @article %>
  <% end %>
<% end %>

<%= para do %>
  And because an article is an <%= inline_code "html.erb" %> file, I can style and format it any way I want <sup><%= link_to "1", "#note-1" %></sup>, without having to build new text editor or preview functionality. I've made things pretty simple for myself, so If I've got something to write, I don't really have any excuses not to turn it into a nice, shiny article.
<% end %>

<%= para extra_class: "mb-8" do %>
  Anyway, that's more or less how this site came into being, and how you're reading this page. Speaking of which, thank you for reading! And feel free to explore the full sourcecode <%= link_to "here", "https://github.com/ollieh-m/blog" %>.
<% end %>

<%= line %>

<%= para extra_class: "mt-4" do %>
  <sup id="note-1">1</sup> including...
<% end %>

<%= para do %>
  <%= code language: :erb do %>
    <%%= para do %>
      <%%= code language: :erb do %>
        ...turning this paragraph into a code snippet that 
        shows the kind of helper methods I've written to make 
        writing an article more convenient
      <%% end %>
    <%% end %>
  <% end %>
<% end %>

app/views/articles/_article_coming_soon_preview.html.erb
<div class="<%= article_card_colour_classes(article) %>">
  <div class="p-4 text-xl font-bold"><%= article.title %></div>
</div>

app/views/articles/_article_preview.html.erb
<%= link_to article, class: article_card_colour_classes(article) do %>
  <div class="p-4 text-xl font-bold"><%= article.title %></div>
  <div class="p-4"><%= l(article.created_at.to_date, format: :long) %></div>
<% end %>

app/views/articles/_grid.html.erb
<div class="grid gap-2 grid-cols-1 sm:grid-cols-2 md:grid-cols-4">
  <% items.each do |item| %>
    <%= yield item %>
  <% end %>
</div>

app/views/articles/index.html.erb
<%= render "grid", items: @articles do |article| %>
  <%= render "#{article.class.name.underscore}_preview", article: article %>
<% end %>

app/views/articles/show.html.erb
<%= render @article, article: @article %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html >
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ollie H-M</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= favicon_pack_tag 'picture.svg' %>
    <style>
      <%= Rouge::Themes::Base16.mode(:light).render(scope: '.highlight') %>
    </style>
  </head>

  <body>
    <%= render "header" %>
    <div class="md:max-w-2xl md:mx-auto my-6 px-4 md:px-0">
      <%= yield %>
    </div>
  </body>
</html>